### ISSUE TITLE
Got error when I run bootstrap.sh

### ISSUE THREAD

**Issue by mawer111** [dragonman225/nast#11]
```
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Bootstrapping 7 packages
lerna info Installing external dependencies
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 2 in 'npdl'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 2 in 'npdl'
```
Please give some help,Thanks!

**Comment by mawer111** [comment]
And I'm trying transform notion open api to nast block.Any suggestions?

**Comment by dragonman225** [comment]
I'm using lerna v3.20.2, maybe you could give it a try.

Install it with

```bash
npm i -g lerna@3.20.2
```

I'm guessing that lerna v4.0.0 has breaking changes, making the bootstrap fail.

**Comment by dragonman225** [comment]
> And I'm trying transform notion open api to nast block.Any suggestions?

You can use [`nast-util-from-notionapi`](https://github.com/dragonman225/nast/tree/master/packages/nast-util-from-notionapi) to transform a Notion page to a [`NAST.Block`](https://github.com/dragonman225/nast/blob/ce2752852a8c747d1eab5d0b903310212aa414d9/packages/nast-types/index.d.ts#L12) tree, and get the block you need from it. Not sure if this is what you want? 🤔

**Comment by mawer111** [comment]
> > And I'm trying transform notion open api to nast block.Any suggestions?
> 
> You can use [`nast-util-from-notionapi`](https://github.com/dragonman225/nast/tree/master/packages/nast-util-from-notionapi) to transform a Notion page to a [`NAST.Block`](https://github.com/dragonman225/nast/blob/ce2752852a8c747d1eab5d0b903310212aa414d9/packages/nast-types/index.d.ts#L12) tree, and get the block you need from it. Not sure if this is what you want? 🤔

Year,I got this.It's a great work.
I want build a module `nast-util-from-notion-open-api`.Get data from notion-open-api and transfrom to NAST.Block tree.I think the officially supported API can be accepted by more people, and there are documents, and it is easier to understand and maintain.
[notion api](https://developers.notion.com/reference/intro)

**Comment by dragonman225** [comment]
Cool! It seems that if `nast-util-from-notion-open-api` is built, it has potential to replace the old `nast-util-from-notionapi`, which is using Notion's private API (`https://www.notion.so/api/v3/`).

You could start by looking into how [`nast-util-from-notionapi`](https://github.com/dragonman225/nast/tree/master/packages/nast-util-from-notionapi/src) is built. Basically it gets all blocks for a page and transform the blocks into `NAST.Block` one by one based on the type of the block.

**Comment by dragonman225** [comment]
There're some tricky things, though. For example, I didn't think thoroughly about links and references when I designed the [NAST types](https://github.com/dragonman225/nast/blob/master/packages/nast-types/index.d.ts), so it has some limitations on representing some newer things like "Synced block", and `nast-util-from-notionapi` is using some [ugly workarounds](https://github.com/dragonman225/nast/tree/master/packages/nast-util-from-notionapi#notice). Another issue is that there're no stable database types in NAST, they're direclty taken from Notion's.

**Comment by dragonman225** [comment]
Hi, I assume the bootstrap issue resolved since the thread has been inactive for a while. If you want to continue working on `nast-util-from-notion-open-api`, feel free to open another issue.
