### ISSUE TITLE
Unable to build nast-util-from-notionapi

### ISSUE THREAD

**Issue by rounakdatta** [dragonman225/nast#5]
Hello @dragonman225, a big thanks for such an awesome project. This is the project that's closest to perfect in maintaining a blog with Notion as CMS. I intended to work on the development of the **recursively allow Page within pages** feature.

To get started, I require to build `nast-util-from-notionapi` locally. However that is failing consistently.

`npm install` -> `npm run-script build` results in the following errors:

```
src/transformCollection.ts:46:7 - error TS2739: Type 'never[]' is missing the following properties from type '{ filters: Filter2[]; operator: FilterOperator; }': filters, operator

46       filter: [],
         ~~~~~~

  node_modules/notionapi-agent/dist/interfaces/notion-models/collection-view/query.d.ts:27:3
    27   filter: {
         ~~~~~~
    The expected type comes from property 'filter' which is declared here on type 'Query2'

src/transformCollection.ts:54:5 - error TS2571: Object is of type 'unknown'.

54     Object.values(queryResult.recordMap.collection)[0].value
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

It would be highly appreciated if you help me with the build procedure. Also please help me with correct versions of node and the project dependencies. Also, please let me know of the challenges you faced in recursively generating corresponding JSONs for the in-page pages.

Otherwise, great work, kudos!

**Comment by dragonman225** [comment]
Those errors are TypeScript type errors, which does not effect the build process. If you could confirm that [the `npdl` package](https://github.com/dragonman225/nast#testing) inside this repo works, you could ignore the errors for now.

**Comment by dragonman225** [comment]
It is recommended to use Node.js v12 or higher.

**Comment by dragonman225** [comment]
Hi, this issue has been inactive for a while, so I'm going to close it.
In the future if you still have problems, feel free to re-open for further discussion.
