### ISSUE TITLE
Is this able to get images out of Notion?

### ISSUE THREAD

**Issue by corysimmons** [dragonman225/nast#6]
Specifically images that we can access (they have a bucket policy that prevent image URLs from working with other Notion npm pkgs I've tried).

**Comment by dragonman225** [comment]
Do you mean downloading the images you uploaded to Notion or Notion's built-in images?

![Screenshot_2020-04-21_02-41-25](https://user-images.githubusercontent.com/25148955/79787541-bdfd5880-8379-11ea-88ef-1fb75b7d5052.png)

Notion's built-in images can always be accessed like this:
`https://www.notion.so/images/page-cover/met_silk_kashan_carpet.jpg`

And for the images you uploaded, if the page you uploaded to is **public**, it can be accessed like this:
`https://www.notion.so/signed/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F4dad0d48-ef9b-431d-8aa3-121fb98fd49a%2F25148955.png?width=296`
(`https://www.notion.so/signed/` + the AWS S3 URL)

**Comment by corysimmons** [comment]
I mean when I write to Notion, I can write Markdown and paste images into it. When I try to fetch the contents of that page, it will give me the HTML/markdown/whatever, but the images are all S3 Bucket Policied so I can't GET them.

I've moved onto using something else for my blogging platform, but I bet the `https://notion.so/signed` prefix would help, so thank you.
